services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: npm install --save three && npm install --save-dev vite && npm install && npm run build
    startCommand: npm run start
